### ISSUE TITLE
Not in the registry

### ISSUE THREAD

**Issue by oazabir** [consulthys/node-red-contrib-logstash#1]
I was trying to install this using npm and I get this error:

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/node-red-contrib-logstash
npm ERR! 404
npm ERR! 404 'node-red-contrib-logstash' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

Would you mind submitting this on the registry?

**Comment by consulthys** [comment]
I initially intended to baseline this repo on Logstash 5, so I was kind of waiting for Logstash 5 to be released (end of October presumably). I definitely have the intention to do this. 
Stay tuned.

**Comment by seb-koch** [comment]
Hi, what is the status here - we are very eager to try it out.

**Comment by consulthys** [comment]
Sorry guys for the delay. Very soon, very soon, promised :-)

**Comment by howardweng** [comment]
this is good and waiting. thanks for your contribution.

**Comment by consulthys** [comment]
This project is obsolete now that the Logstash team is working on a visual pipeline builder
https://discuss.elastic.co/t/any-plans-for-a-visual-logstash-pipeline-editor/54574

**Comment by vfonsecapv** [comment]
I believe that this project can be much more important than what is being done by the Elastic team. I'll hold the fork of your code and continue from here.

**Comment by consulthys** [comment]
@vfonsecapv if you think so, then I'm willing to pursue the effort, I just need to carve out some time, which become more and more difficult.

Anyway, I've regenerated the full list of logstash nodes based on the latest Logstash plugins code base.

@oazabir I've also (finally!!!) submitted the project to the NPM registry.
https://www.npmjs.com/package/node-red-contrib-logstash
